### ISSUE TITLE
parsing a GNUBG ID

### ISSUE THREAD

**Issue by amlwwalker** [gtzampanakis/gnubg#3]
Hey, this is impressive work and clearly a lot went into this. Apologies for this question....
I'm interested in parsing GNUBG IDs however I can't quite get my head around the [algorithm specified here](https://www.gnu.org/software/gnubg/manual/html_node/A-technical-description-of-the-Position-ID.html)

I think this is the [point](https://github.com/gtzampanakis/bgtrain/blob/42250d365a96dc137d05dcf98bfc93294c1dd00f/static/diagram.js#L615) in your code where you are doing it? Is that correct?

GNUBG seems to have a format once the ID is decoded that I can read like:

```json
{
  board: {
    o: {
      "6": 5,
      "8": 3,
      "13": 5,
      "24": 2,
    },
    x: {
      "6": 5,
      "8": 3,
      "13": 5,
      "24": 2,
    },
  },
  cubeful: false,
  dice: [3, 1],
  "max-moves": 3,
  player: "x",
  "score-moves": true,
}
```

I am trying to work out how I can go from the GNUBG ID to a format like this. I can't work out how you are going from the ID to the format that is "human readable" per se and wondered if you might be able to help me extract your algorithm to do so?

**Comment by gtzampanakis** [comment]
The code you are looking for is in the function setDataFromGnuId . Follow it line by line and you will get what you need.

I will close this since it is not an issue. If you have similar questions in the future just email me directly.
